In [1]:
import pandas as pd
import os

In [2]:
env = pd.read_csv("../data/raw/env_air_.csv")
sdg = pd.read_csv("../data/raw/sdg_07_40.csv")

### Modelação do DF: SDG

In [3]:
sdg.head()

,freq,nrg_bal,unit,geo\TIME_PERIOD,2004,2005,2006,2007,2008,2009,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,A,REN,PC,AL,29.620,31.367,32.070,32.657,32.448,31.437,...,36.953,35.776,36.572,38.042,45.015,41.389,44.076,46.620,43.111,NaN
1,A,REN,PC,AT,22.553,24.353,26.276,28.144,28.788,31.039,...,33.370,33.136,33.784,33.755,36.545,34.643,34.057,41.600,42.951,44.2
2,A,REN,PC,BA,NaN,NaN,NaN,NaN,NaN,NaN,...,25.358,23.241,35.972,37.454,39.835,36.587,39.320,40.038,38.524,NaN
3,A,REN,PC,BE,1.916,2.325,2.658,3.140,3.611,4.746,...,8.744,9.136,9.472,9.929,13.000,13.017,13.831,14.673,14.336,14.9
4,A,REN,PC,BG,9.231,9.173,9.415,9.098,10.345,12.005,...,18.760,18.695,20.581,21.545,23.319,19.394,19.079,23.151,23.210,22.7

In [4]:
sdg_long = sdg.copy()
sdg_long = sdg_long.melt(id_vars=["freq", "nrg_bal", "unit", "geo\\TIME_PERIOD"], var_name="year", value_name="percentagem")
sdg_long.head()

  freq nrg_bal unit geo\TIME_PERIOD  year  percentagem
0    A     REN   PC              AL  2004       29.620
1    A     REN   PC              AT  2004       22.553
2    A     REN   PC              BA  2004          NaN
3    A     REN   PC              BE  2004        1.916
4    A     REN   PC              BG  2004        9.231

In [5]:
columns = ["freq", "nrg_bal", "unit"]

for cols in columns:
    if cols not in columns:
        continue
    check = sdg_long[cols].unique()
    if len(check) == 1:
        sdg_long = sdg_long.drop(columns=cols)
        print("Coluna removida:", cols)
    else:
        print(cols, "->", check)

Coluna removida: freq
nrg_bal -> ['REN' 'REN_ELC' 'REN_HEAT_CL' 'REN_TRA']
Coluna removida: unit

In [6]:
sdg_long = sdg_long.rename(columns={
                           	"nrg_bal": "energia_ren",
                            "geo\TIME_PERIOD": "pais"})

sdg_long.head()

  energia_ren pais  year  percentagem
0         REN   AL  2004       29.620
1         REN   AT  2004       22.553
2         REN   BA  2004          NaN
3         REN   BE  2004        1.916
4         REN   BG  2004        9.231

### Modelação do DF: ENV

In [7]:
env.head()

,freq,unit,airpol,src_crf,geo\TIME_PERIOD,1990,1991,1992,1993,1994,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,A,MIO_T,CH4,CRF1,AT,0.05442,0.04970,0.04877,0.04635,0.03954,...,0.03087,0.03084,0.03199,0.02887,0.02811,0.02726,0.02873,0.02657,0.02694,0.02640
1,A,MIO_T,CH4,CRF1,BE,0.05939,0.05471,0.04767,0.04917,0.04371,...,0.03360,0.03342,0.03254,0.03197,0.03242,0.03087,0.03251,0.02870,0.02924,0.02843
2,A,MIO_T,CH4,CRF1,BG,0.09989,0.08456,0.09399,0.09496,0.08775,...,0.06470,0.06125,0.06590,0.06000,0.05644,0.05303,0.05795,0.06133,0.04673,0.03940
3,A,MIO_T,CH4,CRF1,CH,0.01529,0.01563,0.01496,0.01415,0.01324,...,0.00606,0.00601,0.00591,0.00542,0.00527,0.00495,0.00514,0.00455,0.00440,0.00430
4,A,MIO_T,CH4,CRF1,CY,0.00051,0.00052,0.00052,0.00052,0.00054,...,0.00065,0.00067,0.00074,0.00074,0.00077,0.00075,0.00076,0.00079,0.00072,0.00071

In [8]:
env_long = env.copy()
env_long = env_long.melt(id_vars=["freq", "unit", "airpol", "src_crf", "geo\\TIME_PERIOD"], var_name="year", value_name="mio_t_co2eq")
env_long.head()

  freq   unit airpol src_crf geo\TIME_PERIOD  year  mio_t_co2eq
0    A  MIO_T    CH4    CRF1              AT  1990      0.05442
1    A  MIO_T    CH4    CRF1              BE  1990      0.05939
2    A  MIO_T    CH4    CRF1              BG  1990      0.09989
3    A  MIO_T    CH4    CRF1              CH  1990      0.01529
4    A  MIO_T    CH4    CRF1              CY  1990      0.00051

In [9]:
columns = ["freq", "unit", "airpol", "src_crf"]

for cols in columns:
    if cols not in env_long.columns:
        continue
    check = env_long[cols].unique()
    if len(check) == 1:
        env_long = env_long.drop(columns=cols)
        print("Coluna removida:", cols)
    else:
        print(cols, "->", check)

Coluna removida: freq
unit -> ['MIO_T' 'THS_T']
airpol -> ['CH4' 'CH4_CO2E' 'CO2' 'GHG' 'HFC_CO2E' 'HFC_PFC_NSP_CO2E' 'N2O'
 'N2O_CO2E' 'NF3_CO2E' 'PFC_CO2E' 'SF6_CO2E']
src_crf -> ['CRF1' 'CRF1A' 'CRF1A1' 'CRF1A1A' 'CRF1A1B' 'CRF1A1C' 'CRF1A2' 'CRF1A2A'
 'CRF1A2B' 'CRF1A2C' 'CRF1A2D' 'CRF1A2E' 'CRF1A2F' 'CRF1A2G' 'CRF1A3'
 'CRF1A3A' 'CRF1A3B' 'CRF1A3B1' 'CRF1A3B2' 'CRF1A3B3' 'CRF1A3B4'
 'CRF1A3B5' 'CRF1A3C' 'CRF1A3D' 'CRF1A3E' 'CRF1A4' 'CRF1A4A' 'CRF1A4B'
 'CRF1A4C' 'CRF1A5' 'CRF1A5A' 'CRF1A5B' 'CRF1B' 'CRF1B1' 'CRF1B2' 'CRF1D1'
 'CRF1D1A' 'CRF1D1B' 'CRF1D2' 'CRF2' 'CRF2B' 'CRF2B1' 'CRF2B10' 'CRF2B5'
 'CRF2B8' 'CRF2C' 'CRF2C1' 'CRF2C2' 'CRF2C7' 'CRF2D' 'CRF2D1' 'CRF2D2'
 'CRF2D3' 'CRF2G' 'CRF2H' 'CRF3' 'CRF3A' 'CRF3A1' 'CRF3A2' 'CRF3A3'
 'CRF3A4' 'CRF3B' 'CRF3B1' 'CRF3B2' 'CRF3B3' 'CRF3B4' 'CRF3C' 'CRF3C1'
 'CRF3C2' 'CRF3C3' 'CRF3C4' 'CRF3D' 'CRF3E' 'CRF3F' 'CRF3F1' 'CRF3F2'
 'CRF3F3' 'CRF3F4' 'CRF3F5' 'CRF3J' 'CRF4' 'CRF4A' 'CRF4A0' 'CRF4A1'
 'CRF4A2' 'CRF4B' 'CRF4B0' 'CRF4B1' 'CRF4B2' 'CRF4C' 'CRF4C0' 'CRF4C1'
 'CRF4C2' 'CRF4D' 'CRF4D0' 'CRF4D1' 'CRF4D2' 'CRF4E' 'CRF4E0' 'CRF4E1'
 'CRF4E2' 'CRF4F' 'CRF4F2' 'CRF4F4' 'CRF4H' 'CRF5' 'CRF5A' 'CRF5A1'
 'CRF5A2' 'CRF5A3' 'CRF5B' 'CRF5B1' 'CRF5B2' 'CRF5C' 'CRF5C1' 'CRF5C2'
 'CRF5D' 'CRF5D1' 'CRF5D2' 'CRF5D3' 'CRF5E' 'CRF6' 'TOTX4_MEMO' 'TOTXMEMO'
 'CRF1C' 'CRF1D3' 'CRF2A' 'CRF2A1' 'CRF2A2' 'CRF2A3' 'CRF2A4' 'CRF2B3'
 'CRF2B4' 'CRF2B6' 'CRF2B7' 'CRF2C3' 'CRF2C4' 'CRF2C5' 'CRF2C6' 'CRF3G'
 'CRF3H' 'CRF3I' 'CRF4G' 'CRF5F1' 'CRF5F2' 'CRF5F3' 'CRF_INDCO2' 'CRF2B2'
 'CRF2B9' 'CRF2E' 'CRF2E1' 'CRF2E2' 'CRF2E3' 'CRF2E4' 'CRF2E5' 'CRF2F'
 'CRF2F1' 'CRF2F2' 'CRF2F3' 'CRF2F4' 'CRF2F5' 'CRF2F6' 'CRF3B5' 'CRF3D1'
 'CRF3D2' 'CRF4F3']

In [10]:
env_long = env_long.rename(columns={
                            "geo\TIME_PERIOD": "pais"})

In [11]:
env_long = env_long[env_long["year"]>="2004"]
env_long

          unit    airpol   src_crf pais  year  mio_t_co2eq
742252   MIO_T       CH4      CRF1   AT  2004      0.03376
742253   MIO_T       CH4      CRF1   BE  2004      0.03403
742254   MIO_T       CH4      CRF1   BG  2004      0.06039
742255   MIO_T       CH4      CRF1   CH  2004      0.01006
742256   MIO_T       CH4      CRF1   CY  2004      0.00057
...        ...       ...       ...  ...   ...          ...
1855625  THS_T  SF6_CO2E  TOTXMEMO   RO  2024     45.27000
1855626  THS_T  SF6_CO2E  TOTXMEMO   SE  2024     41.70000
1855627  THS_T  SF6_CO2E  TOTXMEMO   SI  2024     12.30000
1855628  THS_T  SF6_CO2E  TOTXMEMO   SK  2024      5.90000
1855629  THS_T  SF6_CO2E  TOTXMEMO   TR  2024    184.43000

[1113378 rows x 6 columns]

In [12]:
env_long[env_long["airpol"]=="GHG"]["unit"].unique()

array(['MIO_T', 'THS_T'], dtype=object)

In [13]:
ghg = env_long[env_long["airpol"]=="GHG"]
paises_mio = set(ghg[ghg["unit"] == "MIO_T"]["pais"].unique())
paises_ths = set(ghg[ghg["unit"] == "THS_T"]["pais"].unique())

print("Só em MIO_T:", paises_mio - paises_ths)
print("Só em THS_T:", paises_ths - paises_mio)
print("Em ambos:", paises_mio & paises_ths)

Só em MIO_T: set()
Só em THS_T: set()
Em ambos: {'NO', 'SE', 'RO', 'IS', 'MT', 'CZ', 'SI', 'BG', 'LT', 'LU', 'HR', 'IT', 'CH', 'FI', 'LV', 'AT', 'CY', 'DK', 'NL', 'IE', 'TR', 'PT', 'DE', 'ES', 'EL', 'SK', 'EU27_2020', 'BE', 'HU', 'EE', 'PL', 'FR'}

In [14]:
env_long = env_long[env_long["unit"] == "MIO_T"]
env_long = env_long[env_long["airpol"]=="GHG"]

In [15]:
paises_com_total = set(env_long[env_long["src_crf"] == "TOTXMEMO"]["pais"].unique())
todos_os_paises = set(env_long["pais"].unique())

print("Sem TOTXMEMO:", todos_os_paises - paises_com_total)

Sem TOTXMEMO: set()

In [16]:
env_long = env_long[env_long["src_crf"] == "TOTXMEMO"]
print(env_long.head())

         unit airpol   src_crf pais  year  mio_t_co2eq
758771  MIO_T    GHG  TOTXMEMO   AT  2004     76.16585
758772  MIO_T    GHG  TOTXMEMO   BE  2004    146.05407
758773  MIO_T    GHG  TOTXMEMO   BG  2004     48.69074
758774  MIO_T    GHG  TOTXMEMO   CH  2004     51.70844
758775  MIO_T    GHG  TOTXMEMO   CY  2004      9.02067

### Criação do Dataset a ser trabalhado

In [17]:
sdg_long["year"].dtype
env_long["year"].dtype

dtype('O')

In [18]:
merged_eu = pd.merge(sdg_long, env_long, on=["pais", "year"], how="inner")
merged_eu = merged_eu.drop(columns=["unit", "airpol", "src_crf"], errors="ignore")
print(merged_eu.head())

  energia_ren pais  year  percentagem  mio_t_co2eq
0         REN   AT  2004       22.553     76.16585
1         REN   BE  2004        1.916    146.05407
2         REN   BG  2004        9.231     48.69074
3         REN   CY  2004        3.071      9.02067
4         REN   CZ  2004        6.773    139.10302

In [19]:
eu27 = ["AT", "BE", "BG", "HR", "CY", "CZ", "DK", "EE", "FI", "FR",
        "DE", "EL", "HU", "IE", "IT", "LV", "LT", "LU", "MT", "NL",
        "PL", "PT", "RO", "SK", "SI", "ES", "SE"]

merged_eu_27 = merged_eu[merged_eu["pais"].isin(eu27).copy()]

paises_encontrados = set(merged_eu["pais"].unique())
paises_27 = set(merged_eu_27["pais"].unique())

print("Em falta:", paises_encontrados - paises_27)
print("Em falta:", set(eu27) - paises_encontrados)

Em falta: {'EU27_2020', 'IS', 'NO'}
Em falta: set()

In [20]:
merged_eu_27["meta_eu"] = 42.5 - merged_eu_27["percentagem"]
merged_eu_27

C:\Users\Artur Albuquerque\AppData\Local\Temp\ipykernel_600\3565945589.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_eu_27["meta_eu"] = 42.5 - merged_eu_27["percentagem"]

     energia_ren pais  year  percentagem  mio_t_co2eq  meta_eu
0            REN   AT  2004       22.553     76.16585   19.947
1            REN   BE  2004        1.916    146.05407   40.584
2            REN   BG  2004        9.231     48.69074   33.269
3            REN   CY  2004        3.071      9.02067   39.429
4            REN   CZ  2004        6.773    139.10302   35.727
...          ...  ...   ...          ...          ...      ...
2515     REN_TRA   PT  2024       14.329     52.14016   28.171
2516     REN_TRA   RO  2024        8.395     64.58247   34.105
2517     REN_TRA   SE  2024       26.399     -6.74422   16.101
2518     REN_TRA   SI  2024        9.242     11.03227   33.258
2519     REN_TRA   SK  2024        9.611     28.92736   32.889

[2268 rows x 6 columns]

In [21]:
merged_eu_27.to_csv("../data/raw/processed/eu_renewable_emissions.csv", index=False)